services:
  - type: web
    name: go-shop-backend
    runtime: go
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: go-shop-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com

databases:
  - name: go-shop-db
    databaseName: go_shop_db
    user: go_shop_user
    region: oregon
    plan: free